### PR TITLE
Update simulation.py

### PR DESCRIPTION
**Pull request by daimonie**
Python dynamically loads imported objects, doesn't it?

Anyway, I mostly wanted to ask what I'm looking at, exactly. Is this a single polymer? RR method? PERM? It seems to be a single one, correct?

### CODE REVIEW

**Comment by danielbouman** [comment]
That object should indeed not be there, but we don't want it were you put it either. The reason is that I use an online IDE where I don't have Matplotlib, Python will give an error when it encounters an importing statement for an object that is not installed.

It is a single polymer using Rosenbluth. But we haven't added the weights yet.

**Comment by daimonie** [comment]
Ah, okay. What IDE is it? Isn't it excruciatingly slow? I know getDataJoy was too slow for my taste.

By now, the weights in our sim are okay, though.

**Comment by danielbouman** [comment]
Currently I use Koding.com. It takes a while to startup but after that the speed is not so bad, our polymer program actually runs faster on my IDE than on my partners Windows laptop ;)

**Comment by daimonie** [comment]
Haha, well done.

We were thinking ours was excruciatingly slow yesterday at the TU, but that was on 'my' laptop.  It's a 2009 laptop project HP EliteBook with severe heating issues. I think that Linux is throttling it like no tomorrow; it ran rather decently at home.

**Comment by daimonie** [comment]
Looking around your code base, I think I see a lot of configuration parameters passed around as arguments to functions. 

Why not make them global variables instead? It's kind of the point of a global variable to do just that :p

**Comment by KDGoodenough** [comment]
You're right, we haven't had a good look at (justified) global constants yet.

**Pull request closed without merging**
